from pathlib import Path

http = Path('market_collector/http_server.py')
s = http.read_text()
s = s.replace('"/aggregates/home-market-overview", "/aggregates/home-market-series",', '"/aggregates/home-market-overview", "/aggregates/home-market-series",\n                "/aggregates/fund-limit-overview", "/aggregates/home-market-collect",')
s = s.replace('    if route == "/aggregates/home-market-series" and data_service:\n        return HTTPStatus.OK, data_service.home_series()\n', '''    if route == "/aggregates/home-market-series" and data_service:\n        return HTTPStatus.OK, data_service.home_series()\n\n    if route == "/aggregates/fund-limit-overview" and data_service:\n        return HTTPStatus.OK, data_service.fund_limit_overview()\n\n    if route == "/aggregates/home-market-collect" and data_service:\n        # On-demand refresh is deliberately collector-local: no CF Worker proxy.\n        try:\n            with ThreadPoolExecutor(max_workers=3) as executor:\n                overview = executor.submit(data_service.home_overview)\n                series = executor.submit(data_service.home_series)\n                limits = executor.submit(data_service.fund_limit_overview)\n                return HTTPStatus.OK, {\n                    "overview": overview.result(),\n                    "series": series.result(),\n                    "limits": limits.result(),\n                    "generatedAt": datetime.now(timezone.utc).isoformat(),\n                    "source": "market-collector-local",\n                }\n        except Exception as exc:\n            return HTTPStatus.SERVICE_UNAVAILABLE, {\n                "error": "local_home_collect_failed", "detail": str(exc),\n            }\n''')
http.write_text(s)

product = Path('market_collector/product_snapshot.py')
p = product.read_text()
needle = '    def quote(self, symbol: str) -> dict[str, Any] | None:\n'
override = '''    def _latest_by_symbol(self) -> dict[str, dict[str, Any]]:\n        try:\n            fallback = super()._latest_by_symbol()\n        except (FileNotFoundError, OSError, ValueError):\n            fallback = {}\n        return {**fallback, **self._product_map()}\n\n    def _latest(self) -> dict[str, Any]:\n        products = self._product_map()\n        if not products:\n            return super()._latest()\n        generated = max((str(row.get("asOf") or row.get("updatedAt") or "") for row in products.values()), default="")\n        symbols = [{\n            **row,\n            "computed_premium_percent": row.get("premiumPercent"),\n            "change_percent": row.get("changePercent"),\n            "previous_close": row.get("previousClose"),\n            "collected_at": row.get("asOf") or row.get("updatedAt"),\n            "iopv_timestamp": row.get("latestNavDate"),\n        } for row in products.values()]\n        return {"generated_at": generated, "symbols": symbols, "source": "fund-products"}\n\n'''
if override not in p:
    p = p.replace(needle, override + needle)
product.write_text(p)

test = Path('tests/test_http_server.py')
t = test.read_text()
t = t.replace('    def kline(self, symbol: str, interval: str, limit: int):', '''    def home_overview(self):\n        return {"marketState": "open"}\n\n    def home_series(self):\n        return {"modes": {"price": {}, "premium": {}}}\n\n    def fund_limit_overview(self):\n        return {"currencyTotals": [], "events": []}\n\n    def kline(self, symbol: str, interval: str, limit: int):''')
insert = '''\n    def test_home_aggregate_routes_are_local(self) -> None:\n        service = FakeMarketDataService()\n        for route in (\n            "/api/market-collector/aggregates/home-market-overview",\n            "/api/market-collector/aggregates/home-market-series",\n            "/api/market-collector/aggregates/fund-limit-overview",\n        ):\n            status, payload = resolve_request(route, self.data_dir, service, proxy_request=lambda *_: self.fail("must not proxy"))\n            self.assertEqual(status, 200)\n            self.assertIsInstance(payload, dict)\n        status, payload = resolve_request(\n            "/api/market-collector/aggregates/home-market-collect", self.data_dir, service,\n            proxy_request=lambda *_: self.fail("must not proxy"),\n        )\n        self.assertEqual(status, 200)\n        self.assertEqual(payload["source"], "market-collector-local")\n\n'''
t = t.replace('\n\nif __name__ == "__main__":', insert + '\nif __name__ == "__main__":')
test.write_text(t)
